# Generated by Django 4.2.12 on 2024-05-09 06:57

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restauranttable',
            name='capacity',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='restauranttable',
            name='table_number',
            field=models.PositiveIntegerField(unique=True),
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('reservation_id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=100)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('reservation_date', models.DateField(default=django.utils.timezone.now)),
                ('reservation_time', models.TimeField(default=django.utils.timezone.now)),
                ('reservation_length', models.CharField(choices=[(1, '1 hour'), (1.5, '1.5 hours'), (2, '2 hours'), (2.5, '2.5 hours'), (3, '3 hours')], default=2)),
                ('number_of_guests', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('status', models.CharField(choices=[(1, 'Confirmed'), (0, 'Cancelled')], default=1)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.restauranttable')),
            ],
        ),
    ]
