# Generated by Django 4.2.12 on 2024-05-09 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_openingtimes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OpeningTimes',
            new_name='OpeningHours',
        ),
    ]
