# Generated by Django 4.2.12 on 2024-05-15 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_exceptionalopeninghours_normalopeninghours_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restauranttable',
            name='table_location',
            field=models.CharField(choices=[(0, 'Inside'), (1, 'Outside')], default=0),
        ),
    ]
