# Generated by Django 4.2.12 on 2024-05-15 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_reservation_table_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='exceptionalopeninghours',
            name='is_open',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='table_location',
            field=models.CharField(choices=[('inside', 'Inside'), ('outside', 'Outside')], default=0),
        ),
        migrations.AlterField(
            model_name='restauranttable',
            name='table_location',
            field=models.CharField(choices=[('inside', 'Inside'), ('outside', 'Outside')], default=0),
        ),
    ]
