# Generated by Django 4.2.12 on 2024-05-24 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_exceptionalopeninghours_is_open_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exceptionalopeninghours',
            options={'ordering': ['date']},
        ),
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ['reservation_date']},
        ),
        migrations.AlterModelOptions(
            name='restauranttable',
            options={'ordering': ['table_number']},
        ),
        migrations.AlterField(
            model_name='exceptionalopeninghours',
            name='closing_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exceptionalopeninghours',
            name='opening_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
