# Generated by Django 4.2.12 on 2024-05-28 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_alter_exceptionalopeninghours_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='reservation_length',
            field=models.FloatField(choices=[(1, '1 hour'), (1.5, '1.5 hours'), (2, '2 hours'), (2.5, '2.5 hours'), (3, '3 hours')], default=2),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default=1),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='table_location',
            field=models.CharField(choices=[('inside', 'Inside'), ('outside', 'Outside')], default='inside'),
        ),
    ]
