# Generated by Django 4.2.12 on 2024-05-29 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0010_alter_reservation_reservation_length_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_date', models.DateField()),
                ('reservation_time', models.TimeField()),
                ('duration', models.FloatField()),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.restauranttable')),
            ],
            options={
                'verbose_name': 'Table Booking',
                'verbose_name_plural': 'Table Bookings',
            },
        ),
    ]
