# Generated by Django 4.2.12 on 2024-05-30 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0011_tablebooking'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='reservation_end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='TableBooking',
        ),
    ]
