# Generated by Django 4.2.12 on 2024-06-14 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0013_reservation_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='customer_name',
            new_name='name',
        ),
        migrations.AddField(
            model_name='reservation',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='reservation',
            name='phone_number',
            field=models.CharField(default='', max_length=20),
        ),
    ]
