# Generated by Django 4.2.13 on 2024-06-18 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0014_rename_customer_name_reservation_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='name',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='reservation',
            name='first_name',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AddField(
            model_name='reservation',
            name='last_name',
            field=models.CharField(default='', max_length=25),
        ),
    ]
