# Generated by Django 4.2.13 on 2024-06-18 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0015_remove_reservation_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default=1, max_length=50),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='table_location',
            field=models.CharField(choices=[('inside', 'Inside'), ('outside', 'Outside')], default='inside', max_length=50),
        ),
        migrations.AlterField(
            model_name='restauranttable',
            name='table_location',
            field=models.CharField(choices=[('inside', 'Inside'), ('outside', 'Outside')], default='inside', max_length=50),
        ),
    ]
