# Generated by Django 4.2.13 on 2024-07-09 17:12

import booking.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0019_remove_reservation_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='reservation_time',
            field=models.TimeField(validators=[booking.models.Reservation.validate_reservation_time]),
        ),
    ]
