# Generated by Django 4.2.12 on 2024-06-12 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allergens', '0002_remove_menuitem_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuitem',
            old_name='contains_celery',
            new_name='celery',
        ),
        migrations.RenameField(
            model_name='menuitem',
            old_name='contains_crustaceans',
            new_name='crustaceans',
        ),
        migrations.RenameField(
            model_name='menuitem',
            old_name='contains_dairy',
            new_name='dairy',
        ),
        migrations.RenameField(
            model_name='menuitem',
            old_name='contains_eggs',
            new_name='eggs',
        ),
        migrations.RenameField(
            model_name='menuitem',
            old_name='contains_fish',
            new_name='fish',
        ),
        migrations.RenameField(
            model_name='menuitem',
            old_name='contains_gluten',
            new_name='gluten',
        ),
        migrations.RenameField(
            model_name='menuitem',
            old_name='contains_lupin',
            new_name='lupin',
        ),
        migrations.RenameField(
            model_name='menuitem',
            old_name='contains_molluscs',
            new_name='molluscs',
        ),
        migrations.RenameField(
            model_name='menuitem',
            old_name='contains_mustard',
            new_name='mustard',
        ),
        migrations.RenameField(
            model_name='menuitem',
            old_name='contains_nuts',
            new_name='nuts',
        ),
        migrations.RenameField(
            model_name='menuitem',
            old_name='contains_peanuts',
            new_name='peanuts',
        ),
        migrations.RenameField(
            model_name='menuitem',
            old_name='contains_sesame',
            new_name='sesame',
        ),
        migrations.RenameField(
            model_name='menuitem',
            old_name='contains_soy',
            new_name='soy',
        ),
        migrations.RenameField(
            model_name='menuitem',
            old_name='contains_sulphur_dioxide_sulphites',
            new_name='sulphur_dioxide_sulphites',
        ),
    ]
