# Generated by Django 4.2.12 on 2024-06-12 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allergens', '0003_rename_contains_celery_menuitem_celery_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuitem',
            old_name='sulphur_dioxide_sulphites',
            new_name='sulphites',
        ),
    ]
