# Generated by Django 4.2.12 on 2024-06-12 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allergens', '0004_rename_sulphur_dioxide_sulphites_menuitem_sulphites'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='section',
            field=models.CharField(choices=[('starters', 'Starters'), ('mains', 'Mains'), ('sides', 'Sides'), ('kids', 'Kids'), ('desserts', 'Desserts')], default='mains'),
        ),
    ]
