# Generated by Django 4.2.12 on 2024-06-12 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allergens', '0005_menuitem_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
