# Generated by Django 4.2.13 on 2024-06-18 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allergens', '0006_menuitem_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='section',
            field=models.CharField(choices=[('starters', 'Starters'), ('mains', 'Mains'), ('sides', 'Sides'), ('kids', 'Kids'), ('desserts', 'Desserts')], default='mains', max_length=50),
        ),
    ]
